### ISSUE TITLE
How to get the final infographic (or at least the same numbers)

### ISSUE THREAD

**Issue by int19h** [JListman/FirearmDeathRate#1]
I'm trying to follow the guidelines in `Regression_Tree_GunDeaths_GunLaws.md` step by step, but it's not clear to me how to go from the plot that it produces (with Z-scored values?) to the data that's presented in the PNG included in the repo (i.e. numbers corresponding to "lives saved"). Could you clarify that final step?

**Comment by JListman** [comment]
"leaves" on the tree plot produced by `rpart` contain predicted number of deaths per 100,000 and the nodes show z-scored values of total count of laws per subcategory. The contents of the tree can also be printed out `print(lawsubcategories_model)`. To get back to total count of laws per subcategory and re-draw the tree (manually), I made a decoder. The decoder `zscore_decoder.rds` is now in the data file of the repo, but I also cleaned up the code and instructions for the decoder in the now updated md file.
